### ISSUE TITLE
What is the target .net framework for this nuget package?? Because i am not able to add this nuget package into my project.

### ISSUE THREAD

**Issue by NewsCurators** [libp2p/cs-libp2p-peer#2]
Also can you please provide some samples containing its usage.

**Comment by tabrath** [comment]
The target is .net standard 1.6. Right now there is a dependency issue preventing me from targeting net45. This is on my todo list as well as documentation.

**Comment by NewsCurators** [comment]
Im trying to use your nugget package in my project but it does not support neither of .net framework 4.5, 4.5.1, 4.6  & 4.6.1. Im not sure how to use it, and im in real need of p2p tool for one of my project. Can you atleast provide me some samples as to which target framework and how to use it.

**Comment by tabrath** [comment]
Sorry to say that it only supports dotnet core at the moment, I'm working on the .net framework support. What's the need for this package, exactly? It's just a small module of a larger project, and what this package provides is just the Id of a Peer in the LibP2P way. If you're only in need for this one class "PeerId" that this package provides, I'd recommend you just pull that one file out by downloading it and adding it to your project until the support for .net framework is done.

**Comment by amarkatti** [comment]
I'm trying to build a peer to peer communication system similar to skype or bitTorrent...I have seen that with centralized server architecture there is lot of delay and performance issues hence looking to build a decentralized system.
Yes, I donno any of these libp2p classes or functionalities, hence I want to explore them. I don't even know if these are stable code or not. Also there are hardly any p2p system code out there in the market.

**Comment by tabrath** [comment]
Actually, the IPFS project is pretty stable if you look at the official implementation (written in C#) and the JavaScript version is coming along. The implementation in C# is only partial and very experimental as those modules/projects are just building blocks to implement IPFS in C#. It's structured similary to the Go and JavaScript implementations. I'd recommend you head over to [ipfs](https://github.com/ipfs), [libp2p](https://github.com/libp2p) and [multiformats](https://github.com/multiformats) if you would to understand more about this project.

**Comment by amarkatti** [comment]
Yes I know about Ethereum and have been working on it from past couple of years.
At the same time I wanted to understand the IPFS and since I am c# developer I was interested in your project. do you have at documentation or sample codes on how to use libp2p / IPFS written in Go ?

**Comment by tabrath** [comment]
As far as I know it's not possible to use libraries written in Go from C#. That's why I started on this project in the first place. If you're looking for a library to just plugin in, I must disappoint you that it's far from ready to be used. If you follow the links in my previous comment and look around for both documentation and implementations you will get the information you need. I suggest you go there because documentation is not #1 priority in this implementation yet.
